/** Authoritative annotation supplement shared by every AI provider and reference retrieval.
 * Worked examples and interaction contract: docs/치수-배치와-곡선-화살표-사용법.md
 */
export const ANNOTATION_GUIDANCE = `
Angle/length annotation rules (current runtime supplement):
- A fresh creation, including a model visual repair, is framed and laid out again at the final viewport before review/application. Use readable base text around 24px; the runtime raises undersized model-proposed point names and measurements unless the teacher explicitly specifies a font size. Existing objects, manual views and patch mode remain pinned. On an empty scene explicitly requesting a coordinate plane, native axes are prepared automatically; do not imitate those axes with helper points or duplicate segments.
- angleDimension supports leaderMode: auto|always|none (default auto), leaderCurvature: -300..300 screen pixels (default 28), labelPlacement: centered|legacy. Use centered for new figures; legacy only preserves old files.
- Keep a readable angle value inside its own angle on the interior bisector; omit an automatic arrow when the whole text box fits there. If a narrow angle, crowded intersection or long expression cannot fit clearly inside, move that angleDimension.labelOffset OUTSIDE the actual triangle/polygon, not merely farther into its interior, and use leaderMode:auto. The runtime draws a curved arrow FROM the text box TO its own angle arc with a small visible gap at the tip. Use always when the user explicitly requests the arrow; none when explicitly unwanted. Never replace this with an independent vector/annotationArrow, duplicate angle, or an arrow pointing at the vertex.
- The arrow follows the text, arc radius and vertex geometry. Change leaderCurvature to route around another label; inspect the actual render for crossings. Do not claim automatic avoidance of all edges. Hidden values do not draw leaders. Preserve existing manual offsets in patch mode.
- When an angle label is explicitly outside with leaderMode:always, keep that exterior placement during automatic layout and visual repair. Do not move it back inside merely because a larger viewport makes room.
- lengthDimension supports curvature (signed screen pixels), dashLength and dashGap (1..40 pixels, defaults 7/7), labelOnCurve (boolean), labelT (0.1..0.9, default 0.5). For new length labels use labelOnCurve:true and omit labelOffset; the text occupies a gap on its curve. Dragging attached text changes curve curvature and its position along the curve. Use labelOnCurve:false only for explicitly free labels or preserved legacy offsets.
- For a new prism drawing, put dimensions on exterior silhouette edges when possible. A base edge and its translated rear counterpart are the same length, as are the corresponding connecting edges of an exact parallel prism projection. The runtime can use one of these equivalent outer anchors without moving vertices or changing values. Do not transfer a measurement to an arbitrary equal-looking edge, and preserve a specifically requested anchor or existing fixed curve.
- Route the full length curve before placing its text: prefer space outside the associated figure, clear of angle arcs, hidden edges and other dimension curves except unavoidable endpoint contact. If a fixed point name blocks the exterior route, use an otherwise empty face without moving the name. New generation can select curve direction/height; manual offsets and explicitly constrained curve heights remain fixed.
- Use readable function/formula text (about 24px for a 1000px drawing), including standalone textLabel formulas such as y=2. Check the complete formula box, not only the first glyph, against graph strokes, axes and other labels. Preserve explicit requested font sizes and existing teacher positions. New equalLengthMarker sizes are bounded automatically from the scene scale and are kept independent of stroke-width changes; distinguish independent groups by tickCount, not arbitrary size.
- Prefer a calm 7px dash / 7px gap, and readable dimension text (new default 24px; use about 24..30px for a 1000px drawing and inspect its ratio to the figure). Print integer measurements without redundant decimals: 40°, 6cm, not 40.0° or 6.0 cm. Preserve genuine fractional values and algebraic expressions. One equal-angle group normally uses one tick per arc; separate independent equality groups with distinct counts. Do not put length numbers away from their dimension curve. Place different side measurements outside the polygon and stagger overlapping measurements.
- Put point names just outside the adjacent polygon angle; point labelOffset is a screen-pixel bottom baseline, dimension labelOffset is a mathematical-coordinate displacement. Preserve teachers' explicit coordinates and offsets. Check letters, arc/text association, dashed gaps and arrow direction in the rendered figure, then verify save/reload.
Examples:
{"op":"update","id":"existingAngle","labelOffset":{"x":-1.2,"y":0.8},"leaderMode":"always","leaderCurvature":24}
{"op":"create","id":"length_AB","type":"lengthDimension","segmentId":"AB","labelOnCurve":true,"labelT":0.5,"curvature":-60,"dashLength":7,"dashGap":8,"labelFontSize":24}
`;
